<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * OrdreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdreRepository extends EntityRepository
{
}
