<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends EntityRepository
{
    public function populateMyList()
    {
        $query = $this->_em->createQuery('SELECT a.id, a.nomVernaculaire, a.nomLatin FROM AppBundle:Taxon a');
        $results = $query->getResult();
        return $results;
    }
}
