<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends EntityRepository
{
}
