<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countFrozenUsers()
    {
        return $this
            ->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.roles = :frozen')
            ->setParameter('frozen', '["ROLE_FROZEN"]')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getFrozenUsers()
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.roles = :frozen')
            ->orderBy('u.dateBan', 'ASC')
            ->setParameter('frozen', '["ROLE_FROZEN"]')
            ->getQuery()
            ->getResult();
    }

    public function countNaturalistesEnAttente()
    {
        return $this
            ->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.roles = :pending_naturaliste')
            ->setParameter('pending_naturaliste', '["ROLE_PENDING_NATURALISTE"]')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getNaturalistesEnAttente()
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.roles = :pending_naturaliste')
            ->setParameter('pending_naturaliste', '["ROLE_PENDING_NATURALISTE"]')
            ->getQuery()
            ->getResult();
    }
}
