# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity:
                class: AppBundle:User
                property: email

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_NATURALISTE]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
                    - app.google_authenticator
                    - app.facebook_authenticator
                entry_point: app.security.login_form_authenticator

            logout:
                path: /logout
            switch_user: ~
            remember_me:
                secret: "%secret%"
                lifetime: 604800
