# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.user_photo_upload_listener:
        class: AppBundle\Doctrine\UserPhotoUploadListener
        arguments: ['@app.uploader', '%user_photo_dir%']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    app.facebook_provider:
        class: League\OAuth2\Client\Provider\Facebook
        arguments:
            -
                clientId: 272372656515794
                clientSecret: afeb75fcb89b2ca310ae61ce209d2b12
                graphApiVersion: v2.8
                redirectUri: "http://localhost:8000/connect/facebook-check"

    app.facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true

    app.google_provider:
        class: League\OAuth2\Client\Provider\Google
        arguments:
            -
                clientId: 880361180991-6h7jq6pv0ott4idiv1nl3dr17o2d4c6v.apps.googleusercontent.com
                clientSecret: 21iDvndTgckLgb70EN36-kvv
                redirectUri: "http://localhost:8000/connect/google-check"

    app.google_authenticator:
        class: AppBundle\Security\GoogleAuthenticator
        autowire: true

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.register_user:
        class: AppBundle\Service\RegisterUser
        arguments: ['@service_container']

    app.validator.username_exists:
        class: AppBundle\Validator\Constraints\UsernameExistsValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }

    app.send_mail:
        class: AppBundle\Service\SendMail
        arguments: ['@swiftmailer.mailer', '@twig', '@doctrine.orm.entity_manager', '%contact_mail%']

    app.createliste:
        class: AppBundle\Service\TaxonList
        autowire: true

    app.profil_user:
        class: AppBundle\Service\ProfilUser
        autowire: true

    app.uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%user_photo_dir%']

    app.observation_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%observations_directory%']

    app.doctrine_observation_listener:
            class: AppBundle\Doctrine\ObservationPhotoUploadListener
            arguments: ['@app.observation_uploader', '%observations_directory%']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }

    app.manage_obs:
        class: AppBundle\Service\ObsManage
        autowire: true